### ISSUE TITLE
Sort of amusing typo: GET /setup/eureka_info?options=detail¶ms=

### ISSUE THREAD

**Issue by vaguerant** [rithvikvibhu/GHLocalApi#10]
Seems like somehow ```&params=``` has become ```&para;ms=```, because that's a paragraph marker ```&para;```: &para;

**Comment by rithvikvibhu** [comment]
Lol I wasn't sure how to document get parameters in url in API Blueprint. So I just put it in the body.
Anyone who can, please comment or submit a PR.

**Comment by rithvikvibhu** [comment]
Thanks @thel3l!
