### ISSUE TITLE
GET /setup/bluetooth/connect (not from your documentation) gives error 405

### ISSUE THREAD

**Issue by vaguerant** [rithvikvibhu/GHLocalApi#12]
I was just goofing around trying out API calls that seemed plausible, and hit on this one which I assume requires a POST request.

**Comment by vaguerant** [comment]
Closing this since @yummypasta's PR was accepted.

**Comment by rithvikvibhu** [comment]
Thanks @vaguerant! Can you look into the endpoint and try to make it work?

**Comment by rithvikvibhu** [comment]
Included in docs
