### ISSUE TITLE
Alarm creation

### ISSUE THREAD

**Issue by SoCuul** [rithvikvibhu/GHLocalApi#130]
Hi! Thanks for all the work you've done documenting this api. I'm wondering, do you know if a route is provided to create alarms on the device?

**Comment by rithvikvibhu** [comment]
Hm at the time (~2018), there wasn't any way to create new alarms in the app, only get and delete. Has that changed now?

**Comment by SoCuul** [comment]
> Hm at the time (~2018), there wasn't any way to create new alarms in the app, only get and delete. Has that changed now?

Where would I look in the app to find the alarm menu?
