### ISSUE TITLE
New param for /setup/eureka_info: audio

### ISSUE THREAD

**Issue by vaguerant** [rithvikvibhu/GHLocalApi#17]
i.e. GET ```/setup/eureka_info?options=detail&params=audio```

Response on my end is ```{"audio":{"digital":false}}```

**Comment by rithvikvibhu** [comment]
Thanks! Will add it. Any idea what it's for?

**Comment by vaguerant** [comment]
Still no idea what audio is for, but I just discovered you can drill down into a specific setting rather than getting all the info using a period.

e.g. ```GET /setup/eureka_info?options=detail&params=build_info.cast_build_revision```

This gives you just the value of ```"cast_build_revision"``` rather than the whole ```"build_info"``` field. Doesn't give any additional information or anything, just ... the specific thing you're asking for.

**Comment by rithvikvibhu** [comment]
I tried it too and same response. It's definitely weird and only happens with `night_mode_params`. For others, it only returns that object. Most likely a bug which will be fixed soon.
