### ISSUE TITLE
/setup/connect_wifi looks like POST, not GET as documented.

### ISSUE THREAD

**Issue by vaguerant** [rithvikvibhu/GHLocalApi#18]
I assume it takes a POST request of an SSID to connect to, or something similar.

**Comment by rithvikvibhu** [comment]
I couldn't capture that particular request properly.
Apparently, even the chromecast has a similar endpoint. Found this in an blog post:

>      POST /setup/connect_wifi HTTP/1.1
>     Host: 192.168.255.249:8008
>     Connection: keep-alive
>     Content-Length: 450
>     Origin: https://cast.google.com
>     User-Agent: Mozilla/5.0 (X11; Linux i686) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/29.0.1547.57 Safari/537.36
>     Content-Type: application/json;charset=UTF-8
>     Accept: */*
>     Accept-Encoding: gzip,deflate,sdch
>     Accept-Language: en-US,en;q=0.8
> 
>     {“bssid”:”5c:0a:xx:xx:xx:xx”,”signal_level”:-42,”ssid”:”myotherssid”,”wpa_auth”:7,”wpa_cipher”:4,”enc_passwd”:”AKWQ1K76dYzBzd5XLCkieFepJq+jvWcDMzTWGud7U66iWpfHS5LN4hhzEEcCdrWGyRC2pw0FRbx6dXUILPr40Os2ysp7AYqIloazqc6JsKAP+aLVv9OW8UpJJTEQVbkgcJiuh9+tPLZrmnHTURWHpXlBuYSJkwZDkW8ywnTcg8+wnrRho6BtMtKyXvNH3QIJhk+nXKHxLh154aMdA9+N3R4ZfH+4SNHrFiHhILXPiBgVmsMCM64kEgNQTRNu3Fzasyfea6XVVaQdWRB2DZC+euapWM1G/Pr9dXz1MraUc2tlEaO1LvDoDmy+08+k/ATwuOQO0DjIExsrEcHQIVXfPY=”}HTTP/1.1 200 OK
>     Access-Control-Allow-Headers: Content-Type
>     Cache-Control: no-cache
>     Access-Control-Allow-Origin: https://cast.google.com
>     Content-Length: 0 
Source: http://www.0xrage.com/?p=162

**Comment by rithvikvibhu** [comment]
The password is encrypted with the device's public key (from eureka_info). We need to see if we can encrypt it ourselves.

**Comment by rithvikvibhu** [comment]
Closing this for now
