### ISSUE TITLE
GET /setup/NOTICE.html.gz

### ISSUE THREAD

**Issue by vaguerant** [rithvikvibhu/GHLocalApi#20]
Hah, this is what happens when you hit the "Open source licenses" button in Device settings in the Home app.

The response is apparently a gzipped web page, and is just the open source licenses, which are read by the Home app directly off the Home device. That's fun.

**EDIT:** Mildly interesting/dangerous: looking at the page's source, it pulls some Javascript off of gc.kis.v2.scr.kaspersky-labs.com over HTTP. Compromise DNS, inject your own Javascript into the Google Home app, ????, profit?

**Comment by kubawolanin** [comment]
> looking at the page's source, it pulls some Javascript off of gc.kis.v2.scr.kaspersky-labs.com over HTTP. Compromise DNS, inject your own Javascript into the Google Home app, ????, profit?

Can't confirm - in my case it's just plain HTML with no dependencies apart of `content.min.css`:
![image](https://user-images.githubusercontent.com/2270505/35138309-3d863168-fcee-11e7-9414-29b332ec80a3.png)

So it might be either some browser extension that injects it locally on your side, or we have different files ;-)
Cheers

**Comment by vaguerant** [comment]
Ah, yep, you're right. I'm currently on somebody else's computer and they have a Chrome extension from Kaspersky that injects their crap.

**Comment by rithvikvibhu** [comment]
Haha interesting. I don't use a lot of extensions because it slows the pages down.

So can this issue be closed?

**Comment by vaguerant** [comment]
I really filed it because of being able to read the licenses off the device, but it's not really part of the API anyway, so I will close.

**Comment by rithvikvibhu** [comment]
Will add this too. We could have a separate section for all static files like this one and that icon.
