### ISSUE TITLE
Connectivity: POST /setup/scan_wifi and GET /setup/scan_results

### ISSUE THREAD

**Issue by vaguerant** [rithvikvibhu/GHLocalApi#22]
Found this endpoint on [this webpage](http://fiquett.com/2013/07/chromecast-traffic-sniffing/) about sniffing traffic on a Chromecast. It works on the Home, too. On that page it's documented as "scan for available wifi" but the result I get from the request only shows one AP, the one the device is currently connected to (there are others in range). I'm not sure what to make of this.

I think everything else on that page is either already documented or doesn't work on Homes.

**Comment by vaguerant** [comment]
Aha. Pulling from [here](https://github.com/dz0ny/leapcast/blob/master/leapcast/services/dial.py), I see there's a ```/setup/scan_wifi```. And from [here](https://www.packetgeek.net/2013/08/google-chromecast-and-scanning-for-wifi-networks/), I see that it takes an empty ```POST``` request. After doing a ```POST /setup/scan_wifi```, ```GET /setup/scan_results``` is now showing all the wifi networks in my area.

I'm guessing this is completely unused behavior, the device should never have any reason to scan for its own wifi as far as I can tell since it's just told by the Home app what network to connect to.

**Comment by vaguerant** [comment]
Sorry for the commentspam, edit field seems to be playing up for me. The Home seems to forget the results of the wifi scan after roughly (exactly?) three minutes. When I checked the results again after making the previous comment, they were back to just listing the connected AP. So I did another  ```POST /setup/wifi_scan``` and sat running ```GET /setup/scan_results``` for the next three minutes until it stopped showing all the other networks.

**Comment by vaguerant** [comment]
More commentspam: there's also ```POST /setup/save_wifi```, found [here](https://plus.google.com/+LeonNicholls/posts/CKWop1P12t8). No idea what you'd do with it, sorry.

**Comment by rithvikvibhu** [comment]
Not spam if it's adding more info :wink: Will add it and try to find more on it

**Comment by rithvikvibhu** [comment]
Okay things are slightly different for me. /setup/scan_results takes slightly longer to respond (compared to other endpoints) and always returns a list of all APs in range. I didn't have to send the POST request before. Something must've changed in 2 weeks.

@vaguerant can you try this again?

**Comment by brannondorsey** [comment]
I can confirm that `GET /setup/scan_results` seems to behave similarly for me as it does for @vaguerant. If the chromecast has been running for a while it only has the network it has connected to in `/setup/scan_results`. But if I reboot or `POST /setup/scan_wifi` it has a full list.

**Comment by rithvikvibhu** [comment]
Looks like I'll be baking another look at this.

**Comment by rithvikvibhu** [comment]
@brannondorsey Sorry about the delay. I still get all APs at `GET /setup/scan_results` even after a few minutes.

Are you using a Chromecast or a Google Home? Things might be a bit different.

**Comment by rithvikvibhu** [comment]
So I guess it's slightly different for Google Home because I tried getting scan results (without scanning first) and it always listed the APs. Good to know.
