### ISSUE TITLE
Device Info(?): POST(?) /setup/send_log_report

### ISSUE THREAD

**Issue by vaguerant** [rithvikvibhu/GHLocalApi#23]
Found in [this Chromecast support thread](https://productforums.google.com/forum/#!topic/chromecast/CtDHehjzzLs;context-place=topicsearchin/chromecast/authorid$3AAPn2wQfKQNfAk2XjJVKzWx2ddLNpwTlv56G-a3GDl4cYInivOE1MdCGS-90GPCE5upq7U1IaV_29%7Csort:date%7Cspell:false). Sorry, I have zero idea what should be ```POST```ed to it or what it's actually for beyond what can be guessed from the name. Attempting a ```GET``` results in ```Error 405: Method Not Allowed```, but an empty or invalid ```POST``` just results in ```404 Not Found```. Perhaps it's neither ```GET``` nor ```POST```?

**EDIT:** Based on [this page](https://www.reverse.it/sample/19c210a098448e3c9acb6a4a77c195bdd1d7004c4a37adfc2efdc1a35eb2ee2e?environmentId=100) which I do not understand *at all* as a lay user, it seems to have something to do with sending crash logs to Google? And perhaps it's triggered by ```POST```ing your UUID to that endpoint? From what I can tell, end users are not supposed to know their UUIDs, so I'm not sure how you'd find that info, assuming I'm even remotely in the ballpark of what this is all about. Quoting from that page in case it dies:
```d.getAllResponseHeaders=function(){return this.ea&&this.Ty()?this.ea.getAllResponseHeaders():""};d.gH=function(){return r(this.Nh)?this.Nh:String(this.Nh)};d.pg=function(a){return a+" ["+this.vJ+" "+this.lp+" "+this.Sa()+"]"};var Bf=function(a,b,c){this.source=a;this.type=b;this.message=c};var Cf=x("mr.DongleUtils"),Df=function(a){return"https://crash.corp.google.com/samples?stbtiq="+a},Ef=function(a,b,c){var e=new tf;e.dO("text");e.Mu(3E5);Xc(e,"complete",function(a){a=a.target;var e,f;a.ie()?(e="ok",f=Df(b)):(e="error",f="Unable to retrieve "+a.ws()+", error = "+a.gH());c(e,f);a.Ya()});e.send("http://"+a+":8008/setup/send_log_report","POST",JSON.stringify({uuid:b}),{"Content-Type":"application/json"});return Df(b)},Ff=null,Gf=function(a){if(!r(a))return Promise.resolve();if(Ff&&Ff.ip==```

**Comment by rithvikvibhu** [comment]
Not sure about this yet. Need to check the app if it can shed some light.

**Comment by rithvikvibhu** [comment]
Didn't find anything. Will reopen if someone gets more info.
