### ISSUE TITLE
Device Settings: POST /setup/multizone/join_group, POST /setup/multizone/leave_group and /setup/multizone/disband_group

### ISSUE THREAD

**Issue by vaguerant** [rithvikvibhu/GHLocalApi#24]
Found in [this forum post](http://forums.slimdevices.com/showthread.php?104383-Chromecast-Audio-ideal-for-Squeezebox-replacement-hardware&p=840880&viewfull=1#post840880).

This seems to be for managing multiple devices, like when you have Google Homes all through the house and want them all to play the same music so you can hear it wherever you go. I only have one Home and no Chromecasts currently, so unfortunately, I really have no way of testing this.

The poster in the above thread gives the following info on the two endpoints:
```
/setup/multizone/disband_group - POSTed and needs json with uuid of group to disband
/setup/multizone/join_group - - POSTed and needs json wit data to create group
```

**EDIT:** Not from that thread but seemed logical, so I tried it and there is also:
```
POST /setup/multizone/leave_group
```

**Comment by rithvikvibhu** [comment]
So I've been distracted with other things for the past 2 weeks and couldn't take a look at this. Will add this in a few minutes.
And thanks for testing and contributing all these new endpoints @vaguerant!

**Comment by rithvikvibhu** [comment]
I have a single Home and can't test this / get more info. Will have find someone for this.

**Comment by yummypasta** [comment]
I can test this. Will PR over when I find suitable data.

**Comment by yummypasta** [comment]
Tested disband_group and leave_group in #26. Still need to find valid data for join_group

**Comment by rithvikvibhu** [comment]
Added in PR #26 by @yummypasta
