### ISSUE TITLE
What is the /setup/offer token used for?

### ISSUE THREAD

**Issue by brannondorsey** [rithvikvibhu/GHLocalApi#27]
> Gets a token which can presumably be used to get offers online. Not used anywhere locally.

Any hunch or evidence of what the offer token provided by `/setup/offer` is actually used for? I'm doing some security research around this undocumented Google Home API and that **screams** red flag. I'd really like to know what this token can be used for.

Great work by the way. Your efforts in documenting this API are amazing. Really appreciated :smile_cat:.

**Comment by rithvikvibhu** [comment]
Couldn't find much. If someone does, I'll open it again.
