### ISSUE TITLE
The local API has changed.

### ISSUE THREAD

**Issue by jordi-7** [rithvikvibhu/GHLocalApi#29]
It now returns a different JSON:
{"bssid":"bssid","build_version":"130671","cast_build_revision":"1.34.130671","closed_caption":{},"connected":true,"ethernet_connected":false,"has_update":false,"hotspot_bssid":"hotspot_bssid","ip_address":"x.x.x.x","locale":"es","location":{"country_code":"ES","latitude":0.0,"longitude":0.0},"mac_address":"mac_address","name":"name","noise_level":-95,"opt_in":{"crash":true,"opencast":false,"stats":true},"public_key":"key","release_track":"preview-joining-stable-channel","setup_state":60,"setup_stats":{"historically_succeeded":true,"num_check_connectivity":0,"num_connect_wifi":0,"num_connected_wifi_not_saved":0,"num_initial_eureka_info":0,"num_obtain_ip":0},"signal_level":-53,"ssdp_udn":"ssdp_udn","ssid":"ssid","time_format":2,"timezone":"Europe/Madrid","tos_accepted":true,"uma_client_id":"uma_client_id","uptime":72490.36,"version":9,"wpa_configured":true,"wpa_id":0,"wpa_state":10}

**Comment by rithvikvibhu** [comment]
Really sorry about the delay. Is this the response for `/setup/eureka_info`? If the `params` GET query isn't sent in the request, then only a subset of details are received. Try this:
```http://<gh-ip>:8008/setup/eureka_info?params=version,audio,name,build_info,detail,device_info,net,wifi,setup,settings,opt_in,opencast,multizone,proxy,night_mode_params,user_eq,room_equalizer&options=detail```

**Comment by jordi-7** [comment]
Yes, that response is for /setup/eureka_info. I get it now, I'll try passing the parameters. Sorry for opening the issue and thanks for your response!
