### ISSUE TITLE
Detailed README

### ISSUE THREAD

**Issue by rithvikvibhu** [rithvikvibhu/GHLocalApi#3]
For both `master` and `gh-pages` branches

**Comment by kubawolanin** [comment]
Hi @rithvikvibhu, thank you so much for documenting the API!
I'd throw in an idea on how to extend the README:

* Clarify that the port should be `8008`. At least for GET requests. I wasn't able to send any POST request though.

Thanks for your work! I'm already looking forward to integrate GH with [openHAB](https://github.com/openhab/openhab2-addons). 

Cheers

**Comment by rithvikvibhu** [comment]
Thanks for the feedback! Yeah that format looks pretty good, will do. 

About the POST requests, was it that you haven't tested them or they don't work?

**Comment by kubawolanin** [comment]
I've tested e.g. the following:
`POST 192.168.0.XXX:8008/setup/assistant/alarms/volume`

And I'm getting 404 within Postman.

`GET 192.168.0.XXX:8008/setup/assistant/alarms` however gives me `200 OK` and the body that I've posted above.

**Comment by rithvikvibhu** [comment]
It works for me. Weird, I'd always thought that the basics things were available everywhere. Can you check your Google Home app? The timer volume slider should be under `(device) Settings -> Alarms & Timers`.

![image](https://user-images.githubusercontent.com/5113343/35033679-824c96ec-fb91-11e7-82e4-7fd181749055.png)

**Comment by kubawolanin** [comment]
Tried with and without Content-Type header:
![image](https://user-images.githubusercontent.com/2270505/35034057-2af2b8fa-fb6d-11e7-9e53-7f5737e0eaa5.png)

**Comment by rithvikvibhu** [comment]
That's definitely weird. What about the Home app? Does it have the slider under Alarms & timers?

**Comment by kubawolanin** [comment]
Yes, it's there. I'll scan it with Wireshark later today and report back.
Thanks!

**Comment by rithvikvibhu** [comment]
Hey just thought of this. Can you try with this user-agent?
`User-Agent: com.google.android.apps.chromecast.app/1.26.30.8 (Linux; U; Android 8.0.0; Nexus 5X Build/OPP4.170623.014)`
Worked for me without changing it, but maybe you're running a newer firmware which checks this too.

**Comment by kubawolanin** [comment]
Same thing:
![image](https://user-images.githubusercontent.com/2270505/35039700-f61d99c6-fb7e-11e7-9765-8aad2ac0d7ab.png)

`eureka_info` gives me the following stats:
```
...
build_version: "106111",
cast_build_revision: "1.29.106111",
version: 9,
...
```

**Comment by rithvikvibhu** [comment]
Since this is going a bit off topic, please create a new issue for this when you sniff your network @kubawolanin
