### ISSUE TITLE
new endpoint: /setup/test_internet_download_speed

### ISSUE THREAD

**Issue by FNCxPro** [rithvikvibhu/GHLocalApi#30]
Sample Request

    POST /setup/test_internet_download_speed
    Content-Type: application/json
    {
        "url": "https://storage.googleapis.com/reliability-speedtest/random.txt"
    }

Sample Response

    HTTP/1.1 200
    Access-Control-Allow-Headers: Content-Type
    Content-Type: application/json
    {
        "bytes_received": 31457280,
        "response_code": 200,
        "time_for_data_fetch": 9554,
        "time_for_http_response": 130
    }

This is used by the Chromecast backdrop (probably very old version of it), and it tests the internet speed, if not obvious by the endpoint url.

**Comment by rithvikvibhu** [comment]
Really sorry for the delay. Just tested it and it works! Providing a url for any file also works.
This is pretty useful for automation. Thanks for creating this issue! I'll add it soon.

**Comment by FNCxPro** [comment]
Sounds good! 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rithvikvibhu** [comment]
Updated.
