### ISSUE TITLE
Delete Alarms error?

### ISSUE THREAD

**Issue by holyspidoo** [rithvikvibhu/GHLocalApi#33]
Trying to post to /setup/assistant/alarms/delete but I keep getting 
```
{
  "error": "JSON with ids required!"
}
```

Has the JSON body format changed? I'm trying with:
```
{
	"ids":"alarm\/xxxxxxxxxxxxx"
}
```

Escaping the / has no effect on the error message though.

**Comment by rithvikvibhu** [comment]
Hey @holyspidoo,
It's actually an array of strings, so this will work:
```json
{
    "ids": [ "timer\/xxxxxxxxxxxxxxx" ]
}
```

**Comment by holyspidoo** [comment]
Thanks! Works!
