### ISSUE TITLE
Set the normal volume

### ISSUE THREAD

**Issue by Aymkdn** [rithvikvibhu/GHLocalApi#35]
This is not an issue but a reference for the ones who would like to set the volume and would search for it here.

It's possible to do it using the Chromecast protocol, for example: https://github.com/thibauts/node-castv2-client/issues/72

**Comment by rithvikvibhu** [comment]
Also, if someone wants to stick to regular rest API calls, this works:

- Switch on night mode for the whole day (say 2 AM to 1:58 AM)
- Control the volume for night mode
