### ISSUE TITLE
Play custom mp3s

### ISSUE THREAD

**Issue by leobel96** [rithvikvibhu/GHLocalApi#36]
This library (https://github.com/horihiro/esp8266-google-home-notifier) permits you to play custom mp3s to your Google home local device. I think it would be great to add this feature also in this local API!

**Comment by rithvikvibhu** [comment]
Hey @leobel96,
This repo is an unofficial documentation which was created by sniffing network packets from the Google Home app.
I am in no way related to Google and can't actually modify any firmware.
You can try requesting this as a new feature by sending a feedback within the Google Home app.

**Comment by leobel96** [comment]
@rithvikvibhu why are you talking about modify firmware? The repo I linked is about a firmware for a microcontroller but I linked it because it can send mp3s/notifications to an ORIGINAL google home device using some HTTP posts. No google home is modified. If you go deep in the code you can extract the right requests and add them to your API.

**Comment by rithvikvibhu** [comment]
@leobel96 I did look into that. These projects/modules basically use a text-to-speech service (Google Translate in this case) and cast an audio file like a regular mp3. This is super useful and I usually use something like https://www.npmjs.com/package/google-home-push (does the same thing).

This however, isn't a Google Home endpoint in the typical sense. GH has a cast service which receives and plays the audio file just like any other cast receiver would. (There are receivers for Android, Windows and MacOS now too, I think)

I wouldn't mind leaving a tip to such things, but the Cast protocol and sdk are pretty popular and don't have to be included here. For more info: https://github.com/thibauts/node-castv2

**Comment by leobel96** [comment]
Thank you, I really appreciate the interest and the time you have spent to understand how it works. If you don't mind add this feature to your API the issue can be closed. Thank you again.

**Comment by Aymkdn** [comment]
I agree with @rithvikvibhu ... This is a cast protocol and not a Google Home endpoint API. I don't really see why it should be added here because they are two different things...
