### ISSUE TITLE
Cast endpoints found in Blaupunkt PMR100

### ISSUE THREAD

**Issue by jonathan3** [rithvikvibhu/GHLocalApi#37]
From a log dump of the Blaupunkt PMR100 speaker I have found references to a number of endpoints:

- /setup/profile_processor/set_profile_processor
- /setup/input/status
- /setup/multizone/aux_in
- /setup/multizone/set_audio_output_delay
- /setup/multizone/input/set_active

This is a device that also has support for Bluetooth and an aux cable, so I assume some of them are to do with this.

I also found the three endpoints already covered by #24.

**Comment by jonathan3** [comment]
Continued looking and found more:

- /setup/play_sound
- /setup/resume_cast
- /setup/save_wifi
- /setup/send_log_report
- /setup/start_nat
- /setup/suspend_cast

**Comment by rithvikvibhu** [comment]
Thanks for posting this!
Would it be possible for you to send the dump with data? I don't have this device and can't try them out.

**Comment by jonathan3** [comment]
Link is good for 7 days.

https://send.firefox.com/download/0bd575ef05af49cf/#vMbbkqaBLfdk2__nuz3k4g

**Comment by rithvikvibhu** [comment]
Thanks, I'll add what those as soon as possible. Mostly by this week.
