### ISSUE TITLE
New official Local API revealed ...

### ISSUE THREAD

**Issue by Apollon77** [rithvikvibhu/GHLocalApi#40]
It could be that things are coming more official ... at least to include local devices as controllable devices ...

https://developers.google.com/actions/smarthome/concepts/local

**Comment by thorleifjaocbsen** [comment]
Not sure if I am reading this right, is this new thing via the cloud? Our use case is to open a brand new chromecast and run api calls directly through the REST at port 8008. Do this new api have something like that? Where I can just scan the network and control casts with no pre configuration ? (casts on ethernet, on WiFi  they need configuration)

**Comment by claytonjn** [comment]
My understanding is that the new local API is for the GH devices to control other 3rd party devices locally, _not_ for you to be able to control the GH devices locally.

**Comment by rithvikvibhu** [comment]
Yeah, as @claytonjn says, this is mostly for different services like IoT device manufacturers like Philips. Any action can be pushed to a device through GH instead of a 3rd party cloud.

This repo is for controlling GH itself, locally.
