### ISSUE TITLE
Home hub /setup/scan_results returns 403

### ISSUE THREAD

**Issue by joepagan** [rithvikvibhu/GHLocalApi#43]
Running: `curl -vvv -H "Content-Type: application/json" http://192.168.xx.xx:8008/setup/scan_results` responds in a 403, not sure if I'm missing something here?
```
*   Trying 192.168.xx.xx...
* TCP_NODELAY set
* Connected to home.hub (192.168.xx.xx) port 8008 (#0)
> GET /setup/scan_results HTTP/1.1
> Host: home.hub:8008
> User-Agent: curl/7.54.0
> Accept: */*
> Content-Type: application/json
>
< HTTP/1.1 403 Forbidden
< Content-Length:0
<
* Connection #0 to host 192.168.xx.xx left intact
```

**Comment by joepagan** [comment]
Ah sorry for the noise, just seen your other open github issue #39  and https://gist.github.com/rithvikvibhu/1a0f4937af957ef6a78453e3be482c1f

**Comment by rithvikvibhu** [comment]
That reminds me to add a link in the readme.
