### ISSUE TITLE
Zolo Mojo speaker toke,

### ISSUE THREAD

**Issue by magicse** [rithvikvibhu/GHLocalApi#49]
You can very easily obtain the authorization token on Zolo Mojo audio speakers in the following way. Without any HomeGraph ))))
http://192.168.x.x:8008/setup/offer

**Comment by rithvikvibhu** [comment]
1. That api endpoint can't be accessed over http. To use it over https, the local authz token is needed, which defeats the purpose.
2. The token returned here is not the same authz token used to make requests. It is a base64 encoded message that is used to redeem offers linked to the device (like 6-month Google Play music subscription a few years ago). The authz token we need is always 108 characters long. This is much longer.

**Comment by magicse** [comment]
It's funny. but on Mojo Zolo this end point accessible over simple http. 8008 I have tested this and this work. 
I get token and after that make settings via 8433 port.

**Comment by rithvikvibhu** [comment]
This local token only applies to Google devices.

Since 8008 works, I think, in this case, the token you're sending isn't being used at all. Try changing say a single character in the token. Any request will probably work even with the wrong token.
