### ISSUE TITLE
Unexpected build error(Ubuntu 20.04)

### ISSUE THREAD

**Issue by Netger** [rithvikvibhu/GHLocalApi#50]
I'm new to nodejs, so I might ask a stupid question, but I'm getting an error while building the site.
Ubuntu Server 20.04 LTS
nodejs  v10.19.0
npm 6.14.4
>root@server1:/home/server1/GHLocalApi# npm run build
>
> ghlocalapi@2.0.0 build /home/server1/GHLocalApi
> redoc-cli bundle --ssr --title 'Google Home Local API' --output dist/index.htm                                                                                         >l GoogleHome.openapi3.json
>
>sh: 1: redoc-cli: not found
>npm ERR! code ELIFECYCLE
>npm ERR! syscall spawn
>npm ERR! file sh
>npm ERR! errno ENOENT
>npm ERR! ghlocalapi@2.0.0 build: `redoc-cli bundle --ssr --title 'Google Home Lo                                                                                         >cal API' --output dist/index.html GoogleHome.openapi3.json`
>npm ERR! spawn ENOENT
>npm ERR!
>npm ERR! Failed at the ghlocalapi@2.0.0 build script.
>npm ERR! This is probably not a problem with npm. There is likely additional log                                                                                         >ging output above.
>npm WARN Local package.json exists, but node_modules missing, did you mean to in                                                                                         >stall?
>
>npm ERR! A complete log of this run can be found in:
>npm ERR!     /root/.npm/_logs/2020-08-04T16_45_21_305Z-debug.log

**Comment by rithvikvibhu** [comment]
Dependencies have to be installed with `npm install` first before generating docs.
