### ISSUE TITLE
Local Auth token

### ISSUE THREAD

**Issue by markfoodyburton** [rithvikvibhu/GHLocalApi#52]
I have been struggling for a few days to extract the local auth token.
(Following https://rithvikvibhu.github.io/GHLocalApi/#section/Google-Home-Local-API/Authentication)
I am able to get Master and Access tokens
However, when I attempt to get the local auth token, I get the Device name, but an empty token.

I suspect either an issue with the protocol files, or there is no local auth token assigned. 

(The device in question is refusing to come out of 'configuration',  using the "google home" app. So, maybe - perhaps - the issue is indeed at the server end, that for some reason, the google account isn't recording a local auth token ?)

Any hints or tips most welcome !

**Comment by rithvikvibhu** [comment]
Interesting.
This only applies to Google Home (and similar Google) devices, not other integrated services (like Philips Hue, etc.) Can you confirm that it is one?

Also, what's this 'configuration' mode?

**Comment by markfoodyburton** [comment]
Yes - this is a google home mini V1.
The device was factory reset, and now says "you need to download the google home app and configure ..."
Right now, we have tried 100 times in 100 different ways to run the google home APP, and "configure" the device, it all seems to work (including an update), but at the end, when you say OK google, we're back to square one, it says it needs configuring again.

Others call this the "Not Set Up" issue:
https://support.google.com/googlenest/thread/2029712?hl=en&msgid=6315878

My thought was to TRY and get the device out of this state by forcing the eureka_info somehow - I haven't got that far yet.... but maybe the problem is actually on the auth side?

**Comment by rithvikvibhu** [comment]
Aw, that sucks.
`/setup/eureka_info` is special and does not need auth as it is probably used while setting up the device (check the HTTP protocol and port). Does it work for you?

```
curl --location --request GET 'http://192.168.0.23:8008/setup/eureka_info?params=version,audio,name,build_info,detail,device_info,net,wifi,setup,settings,opt_in,opencast,multizone,proxy,night_mode_params,user_eq,room_equalizer,sign,aogh,ultrasound,mesh&options=detail,sign&nonce=1234512345'
```

What's the output you get for `/setup/assistant/check_ready_status` ([docs](https://rithvikvibhu.github.io/GHLocalApi/#operation/CheckReadyStatus))? This is also used when setting up devices to only list ones that haven't been configured yet.

**Comment by markfoodyburton** [comment]
Interesting !
{"can_enroll":false,"enrollment_state":4,"error":"Device is still booting up.","error_code":5,"ready":false,"retryable":true}* Closing connection 0

**Comment by markfoodyburton** [comment]
full eureka info

{"bssid":"e0:91:f5:d6:38:40","build_version":"218411","cast_build_revision":"1.49.218411","closed_caption":{},"connected":false,"ethernet_connected":false,"has_update":false,"hotspot_bssid":"FA:8F:CA:60:D1:7A","ip_address":"192.168.1.210","locale":"en-US","location":{"country_code":"FR","latitude":255.0,"longitude":255.0},"mac_address":"44:07:0B:74:F9:14","name":"Kitchen speaker","opt_in":{"crash":false,"opencast":false,"stats":false},"public_key":"MIIB ..... DAQAB","release_track":"stable-channel","setup_state":52,"setup_stats":{"historically_succeeded":true,"num_check_connectivity":25,"num_connect_wifi":18,"num_connected_wifi_not_saved":0,"num_initial_eureka_info":10,"num_obtain_ip":19},"ssdp_udn":"0ca0c584-1df2-6a79-5648-76c7d0e14696","ssid":"HelenAndMark","time_format":2,"timezone":"Europe/Paris","tos_accepted":true,"uptime":166908.817669,"version":10,"wpa_configured":true,"wpa_id":1,"wpa_state":10}%

**Comment by rithvikvibhu** [comment]
Hm, something with the device then. I don't really know about the whole setup process, so can't do that without the app.

The `"error":"Device is still booting up."` could mean the device hasn't started yet. How long has it been since the last power on? Giving at least 2 minutes might get this to work.

**Comment by markfoodyburton** [comment]
Tried plenty of things - all wit the same result - seems I have this error code '5', and no way to know what that actually means.... I asked google, but it said I need to configure it . . . :-) :-)

I've tried leaving it off for 20 mins, then booting it. I've tried leaving it off and then doing a FRD (manually).
I've tried a software reboot.
I can't do a software FDR because I have no local auth token (doh).

I've left it for e.g. 20 min's after it "boots" - all to no effect....

seems like I might have hit the bumpers on this one. Which is a bummer - the machine was working fine till it got reset !
I can't believe this is a h/w bug, I can't help thinking that the software update screwed up somewhere along the path.... but I see no obvious solution :-(

**Comment by rithvikvibhu** [comment]
I can't think of anything to fix this or make it work, sorry.

>I can't help thinking that the software update screwed up somewhere along the path

Yeah, most likely. Try contacting support, I guess.

**Comment by markfoodyburton** [comment]
Thanks for helping anyway - yeah - I still think it's a s/w issue, and support is as helpful as a chocolate tea pot :-(

**Comment by rithvikvibhu** [comment]
Well, all the best. Closing this issue. If you ever figure out, what error 5 is, I'd like to add it to the docs :)

**Comment by markfoodyburton** [comment]
FYI - If you see this error - MAYBE I have the answer !!!
After much to-fro with Google support, they advised me to ADD a secure key to my WiFi (I had specifically been running the wifi network open to eliminate password issues). Securing the network allowed the google home to connect !

I guess other people's millage may vary, and this seems like the strangest behaviour, but - perhaps error_code 5 is "network non-secure" ?

**Comment by rithvikvibhu** [comment]
Ah, I see. Glad it's working for you :p

> perhaps error_code 5 is "network non-secure"

Searching online, there aren't any cases where people have successfully connected to open networks (at least, nothing I could find). So it's definitely possible.
