### ISSUE TITLE
{'Error': 'BadAuthentication'}

### ISSUE THREAD

**Issue by HITChris** [rithvikvibhu/GHLocalApi#54]
Hi. Does anything in particular need to be done for gpsoauth to be able to successfully return a master token? I keep getting this error against a 2FA enabled account.

```
from gpsoauth import perform_master_login, perform_oauth
res = perform_master_login('<mygmail', 'mygmailpwrd', 'myandroidid')
print (res)
```

[*] Getting master token...
{'Error': 'BadAuthentication'}
[!] Could not get master token.
[*] Master token: None

**Comment by rithvikvibhu** [comment]
Yup. With a 2FA account, use an app password from https://myaccount.google.com/apppasswords

For others (not using 2FA), enable less secure apps at https://myaccount.google.com/lesssecureapps

**Comment by HITChris** [comment]
I apologize for being a pain, but can you think of anything else? I've tried every variation I can think of (2FA w/ either gmail account pwd or custom app pwd, as well as non-2FA w/ less_secure enabled + gmail pwd or app pwd), sometimes even with a hardcode device_id (from my Android), and I get the same response each time.

**Comment by rithvikvibhu** [comment]
Just to make sure, you're using just the username right? Not the complete email. Leaving out the `@gmail.com`

**Comment by HITChris** [comment]
Yessir. Running get_tokens.py, with just vars USERNAME and PASSWORD edited to mirror my <username> + (w/ 2-step-enabled attempts) <apppassword>. Neither contain special characters. Attempts with a 2nd google account also fail, so you'd think this would just be user error on my part, but I can't see how.

**Comment by rithvikvibhu** [comment]
I can't think of anything else.
Came across this and saw you've already replied. https://github.com/simon-weber/gpsoauth/issues/24
Hopefully, they'll be able to figure it out.

**Comment by julo15** [comment]
I'm running into this as well. Tried with a 2FA account and a non-2FA account, with app passwords (and non-app passwords).

I'm on Mac, FWIW.

**Comment by rithvikvibhu** [comment]
### For anyone new seeing this issue

Verify:
- Do you have 2FA enabled? If so, then create an app password and use that instead.
- Make sure the USERNAME variable is just the username, not the complete email address (~@gmail.com~).
- Are the overrides unchanged? (all of them set to None is fine).

If it still doesn't work, then it probably is the same bug gpsoauth mentioned above. Track the issue in their repo. As of this comment, it looks os-dependent, not clear.

**Comment by vzRowan** [comment]
I'm still getting the same error on macOS. Since 2 months have passed, is there any solution for this?

**Comment by rithvikvibhu** [comment]
@vzRowan have you seen https://github.com/rithvikvibhu/GHLocalApi/issues/54#issuecomment-720227349 and still face the same problem? If yes, no one knows what the exact problem is, but trying a different computer has worked for some.

**Comment by vzRowan** [comment]
@rithvikvibhu I tried it on my Windows PC yesterday, but got the same error. I guess i'll have to wait for a solution to come up.

**Comment by chvancooten** [comment]
Odd, my cron script for getting tokens based on this repo also suddenly stopped working after a password change. When trying to get a new master token I also face this issue. Tried with real and app password, on three different devices (1x windows 2x linux). All return the bad auth error 🤔 

If anyone manages to fix this issue I'm very happy to hear how!

**Comment by rithvikvibhu** [comment]
I can confirm that with a custom device id (pick any mac address, without colons, all lowercase) + 2FA enabled account + app password works on Manjaro with python 3.8.6 and `gpsoauth 0.4.1`. Can someone try with this specific version of gpsoauth?

**Comment by chvancooten** [comment]
@rithvikvibhu Whoa this is weird. Your comment prompted me to try different Python versions. For me it did **not** work on Python 3.7.5 (on Ubuntu) or 3.8.6 (on Windows/Kali Linux), but it _does_ work on Python 3.6.9 on Ubuntu.

Made no changes otherwise, so may be worth a try to play with different Python versions for the people encountering this issue!

**Comment by vzRowan** [comment]
Tried with Python 3.6.9 and gpsoauth 0.4.1 on Ubuntu but no luck.

**Comment by vzRowan** [comment]
Update: I read on the gpsoauth repo that downgrading to `requests 2.23.0` worked for someone. So i tried this on my Mac with `gpsoauth 0.4.1` and `python 3.6.9` and it seems to work!  Although i haven't tested the tokens i retrieved. But i think it's worth a try for others.

So try `pip install requests==2.23.0` and running the script again.

**Comment by HITChris** [comment]
Downgrading requests has resolved my longwithstanding issue as well (although I likewise haven't had a chance to test the tokens being retrieved).

**Comment by rithvikvibhu** [comment]
Glad to hear! Can you mention which requests version did not and did work? I'll mention that somewhere.

Btw mine was always working and I confirmed working with all versions from 2.23.0 to 2.25.1 (https://requests.readthedocs.io/en/latest/community/updates/#release-history)

Someone with the problem please try this and see which ones don't work:
```sh
python --version

pip install requests==2.23.0
python script.py
pip install requests==2.24.0
python script.py
pip install requests==2.25.0
python script.py
pip install requests==2.25.1
python script.py
```

**Comment by DataPools** [comment]
Getting BadAuth on Ubuntu Server 16.04, `python 3.5.2`, `requests 2.23` and `requests 2.25`

Is there any way to bypass this process together and generate an access token from the normal oauth login page and a scope?

**Comment by rithvikvibhu** [comment]
@DataPools Not that I'm aware of. You could try recreating the same request that the `gpsoauth` package sends. The request and payload is here https://github.com/simon-weber/gpsoauth/blob/master/gpsoauth/__init__.py

**Comment by velkrosmaak** [comment]
I'm still getting this on the latest version of python 3.6, with various versions of requests. I've also clocked continue here: https://accounts.google.com/DisplayUnlockCaptcha though I have created an app specific password since I use 2FA.

**Comment by rithvikvibhu** [comment]
@velkrosmaak do you have another account to try with? If that works, then can compare what's different with the accounts.

**Comment by velkrosmaak** [comment]
I don't have another Google account where my Nest devices are linked to,
but I could try with a different account that doesn't have 2FA set up
either. Will report back!

**Comment by HITChris** [comment]
See simon-weber/gpsoauth#24, this should be resolved

**Comment by Tony450** [comment]
Hello, is this script still working as of April, 2023? I am having the "Bad Authentication" problem and I haven't been able to solve it yet. I have followed the steps that are explained in the comments but it doesn't work.

**Comment by rithvikvibhu** [comment]
@Tony450 I would check with https://github.com/simon-weber/gpsoauth to see if it works and if not, create an issue there.
