### ISSUE TITLE
Python-only script to get auth tokens

### ISSUE THREAD

**Issue by rithvikvibhu** [rithvikvibhu/GHLocalApi#57]
@SoulEater45 (I think) sent a message on Twitter, but I can't reply there, probably their privacy settings.

>...getting information from the homegraph api, where you used the tool grpcurl. Is there a reason you didn't implement that also in python

This is possible, but I just wanted to get it working as soon as possible and gpgcurl just made debugging very easy. Now that the request and the proto file are known to work, it should be easy to use it and generate a regular python (or any other lang) sdk with gRPC.

https://grpc.io/docs/languages/python/quickstart/

I'm currently not free to build this, but if someone does it, please post it here. I'll be happy to link to their guide/sdk.

**Comment by SoulEater45** [comment]
Yes, that would have been me!
Sorry, didn't think about this option of communication, which is much better xD

But yeah, I am quite hopeless regarding the implementation of the grpc api access in python!
So any help would be nice :)

**Comment by SoulEater45** [comment]
@rithvikvibhu I have a little question.
I think I am nearly there with the python implementation, but I do not understand the following snippet from the proto file:
```
message GetHomeGraphRequest {
  string string1 = 3;
  string num2 = 4;
}
```
What do the `string1` and `num2` represent here and should I care about the field numbers 3 and 4 here?

**Comment by rithvikvibhu** [comment]
I've seen that particular request being sent with and without the 2 fields. Both return the same response, I just added them for reference. Since both are optional, it's safe to send an empty body.
