### ISSUE TITLE
could not get access token - wrong logindata?

### ISSUE THREAD

**Issue by anxious77** [rithvikvibhu/GHLocalApi#61]
I'm new to this and was trying your get_tokens.py to get the tokens to access the setup/reboot route to force my chromecast for "foreground ota" because its stuck at a 1.42 firmware.

I filled in my google accountdata (mail & pw) in the script but it always says "could not get access token".

Maybe I missed a few steps?
Would be nice if you can add these in the documentation.

Thanks a lot.

**Comment by rithvikvibhu** [comment]
Do you have 2FA enabled? If so, then create an [app password](https://myaccount.google.com/apppasswords) and use that instead.
Make sure the USERNAME variable is just the username, not the complete email address (~@gmail.com~).
Are the overrides unchanged? (all of them as None are fine).

>but it always says "could not get access token".

So does it successfully print the master token then? This should happen before attempting to get the access token.

**Comment by anxious77** [comment]
First of all thanks for all your work and the response!
It was my username ... I did the mistake with emailaddress. Everything works fine, thank you :-)


Feedback:
In case of some "newbies" like me you could add that its needed to install "jq" to run the - in my case on mac os .. I needed to "brew install jq" to run the protos script :-) otherwise it will fail with "unknown command jq"

**Comment by anxious77** [comment]
One more question because, maybe you can help.
I used your solution to do a force update via ota foreground.

I managed to do this... it reboots and starts via 0% but after a few seconds it says network problem.

So for me there is a problem with my software on Chromecast. I needed to do a factory reset because of a new wlan router etc. So I did a reset and reconnected it, I can stream Netflix etc. but when I force to update it says network problem.

I dont get that.

I need to do a update to 1.44 because of an other app which has compatibility problems.

**Comment by rithvikvibhu** [comment]
Thanks, will be sure to add the username and a note about jq in the docs and examples.

As for the update problem, I have no idea here. Since the rest of the apps load fine, it's not an internet problem. Could be a software thing, maybe contact Google support.
