### ISSUE TITLE
Incomplete example/instruction

### ISSUE THREAD

**Issue by Edo78** [rithvikvibhu/GHLocalApi#63]
I'm trying to check if I can make this works but I found a minor issue and a bigger one looking at the example https://rithvikvibhu.github.io/GHLocalApi/#section/Google-Home-Local-API/Example

The minor one is that isn't reported `jq` as a prerequisite.

The bigger one is that I can't find any info about the content of `/path/to/protos` in
```
./grpcurl -H 'authorization: Bearer ya29.a0Af****' \
  -import-path /path/to/protos \
  -proto /path/to/protos/google/internal/home/foyer/v1.proto \
  googlehomefoyer-pa.googleapis.com:443 \
  google.internal.home.foyer.v1.StructuresService/GetHomeGraph | jq '.home.devices[] | {deviceName, localAuthToken}'
```

I was lucky enought to find https://github.com/rithvikvibhu/GHLocalApi/issues/39#issuecomment-644959103

I don't know why the protos aren't available or mentioned elsewere (that I can found) but it was pretty hard to figure it out as I never user `grpcurl`

I think that the instruction should be updated. Let me know if I can work on a PR

**Comment by rithvikvibhu** [comment]
>isn't reported jq as a prerequisite

Ah yes, I think there was another issue about `jq` not being installed. Will add a comment with each example.

>can't find any info about the content of /path/to/protos

The drive link is listed under prerequisites. Maybe adding a note that `/path/to/protos/` should point to the Proto files folder will clear things up.
![image](https://user-images.githubusercontent.com/5113343/98824229-0fc21900-2459-11eb-8db6-7d7e080b6ebd.png)

**Comment by rithvikvibhu** [comment]
>Let me know if I can work on a PR

Yes, please. I'll merge it when you make one.
