### ISSUE TITLE
GRPCURL

### ISSUE THREAD

**Issue by JMagner97** [rithvikvibhu/GHLocalApi#66]
grpcurl -H 'authorization: Lorenzo aas_et.***' -import-path /Go/google/ -proto /Go/google/internal/home/foyer/v1.proto googlehomefoyer-pa.googleapis.com:443 google.internal.home.foyer.v1.StructuresService/GetHomeGraph | jq '.home.devices[] | {deviceName, localAuthToken}'

When I run this command it returns to me:
"{localAuthToken}' and {deviceName}" are not recognized as external or internal command.

I've already installed jq. 
Thank you for answers.

**Comment by rithvikvibhu** [comment]
I just tried this and it works:
```
./grpcurl -H 'authorization: Bearer ya29.a0Af***' -import-path /home/path/to/protos -proto /home/path/to/protos/google/internal/home/foyer/v1.proto googlehomefoyer-pa.googleapis.com:443 google.internal.home.foyer.v1.StructuresService/GetHomeGraph > /tmp/out.log | jq '.home.devices[] | {deviceName, localAuthToken}'
```

Looking at the error, it looks like the quotes aren't placed correctly. Check that the single quotes are only around the auth header and after jq (and not after `localAuthToken}`)

Also, the auth header should be `authorization: Bearer <access_token>` not the master token. The access token starts with `ya29.`

**Comment by JMagner97** [comment]
Hi thanks for your quick answer:
Still not working. We've tried with this command line and it's not working.

grpcurl -H 'authorization: Lorenzo ya29.***' -import-path /Go/google/ -proto /Go/google/internal/home/foyer/v1.proto googlehomefoyer-pa.googleapis.com:443 google.internal.home.foyer.v1.StructuresService/GetHomeGraph > /tmp/out.log | jq '.home.devices[] | {deviceName, localAuthToken}'

We have the same error that I posted before.

Other question: in which path do you run this command? because I put "grpcurl" and not "./grpcurl". If I put "./grpcurl" gives me error about "." 
Thanks a lot.

**Comment by rithvikvibhu** [comment]
The path is fine, I don't have the grpcurl binary in PATH so need the relative path.

Try using double quotes instead of single after jq. And if it still doesn't work, remove `| jq` and everything after it. All it does is filter the json fields.

Also, the authorization header must begin with `Bearer`, not `Lorenzo`.

**Comment by JMagner97** [comment]
Now it works, I have two kind of results.
1) If I remove | jq and everything after it. I obtain all the list
2) If I put the filters with two quotes I have this error "jq: error (at <stdin>:692): Cannot iterate over null (null)"
If I see all the list I don't find l localAuthToken and nameDevice.
Thanks for your time.
