### ISSUE TITLE
Local auth token

### ISSUE THREAD

**Issue by TorreJoJo** [rithvikvibhu/GHLocalApi#67]
After I run this command line script for get local auth token:

`grpcurl -H "authorization: Bearer ya29.**" -import-path /user/google/ -proto /user/google/internal/home/foyer/v1.proto googlehomefoyer-pa.googleapis.com:443 google.internal.home.foyer.v1.StructuresService/GetHomeGraph | jq ".home.devices[] | {deviceName, localAuthToken}"`

The script output is an error because, if I run the script without jq | etc.  I get an huge list but there aren't deviceName and localAuthToken. 

How can I get localAuthToken by this script and then using to make request with 
`curl -H "cast-local-authorization-token: LOCAL_AUTH_TOKEN" --verbose --insecure https://192.168.0.18:8443/setup/bluetooth/status`

Thanks

**Comment by rithvikvibhu** [comment]
What do you get with `| jq ".home.devices"`? How many objects are listed?

If there aren't any, then no devices are registered with this account. Maybe it's a different Google account.

**Comment by TorreJoJo** [comment]
If I don't put `| jq ".home.devices"` I get a list with 

```
{
  "timestamp1": "1607076292371",
  "home": {
    "homeId": "74bad409-86c8-463f-9368-***********",
    "homeName": "Giovanni",
    "location": {

    }
```
Where homeName it's actually my name of google home. But I don't have local auth token.
If I put `| jq ".home.devices"` it returns null.

```
"linkedUsers": [
      {
        "emailAddress": "_myemail_"
      },
      {
        "emailAddress": "_mysecondemail_"
      }
    ],
```
I had also my email displayed when I don't put `| jq ".home.devices"` on script command line.
Thanks

**Comment by rithvikvibhu** [comment]
The whole structure is like this:
```js
{
    home: {
        homeId: 'xyz',
        homeName: '<HomeName>',
        location: {},
        linkedUsers: [{}, ...{}],
        devices: [
            {
                deviceName: '<Name>',
                localAuthToken: '<Token>',
                linkedUsers: [{}, ...{}],
            }
        ]
    }
}
```

>Where homeName it's actually my name of google home

What's shown in your first code block is the name of the Home (like a bunch of devices together), not the Device's name. Multiple devices can be assigned to a Home. And if it doesn't list any devices, then the device isn't registered to this home.

Since `| jq ".home.devices"` is null, it means that there are no devices in this home. You mention using multiple emails. It's possible that the device is in a different Home on the other account.

**Comment by TorreJoJo** [comment]
Ok but I did it with my second account because with the first account the file get_tokens.py doesn't work because it gives me null fields on access token and master token

**Comment by rithvikvibhu** [comment]
Do you have 2FA enabled? If so, then create an [app password](https://myaccount.google.com/apppasswords) and use that instead.
Make sure the USERNAME variable is just the username, not the complete email address (~@gmail.com~).
Are the overrides unchanged? (all of them as None are fine).

**Comment by TorreJoJo** [comment]
One last question if I tried to make `http://example.com/setup/bluetooth/scan_results` it returns `[]` even if my phone is connected to Google Home. About 2FA enabled now it works
Thank You

**Comment by rithvikvibhu** [comment]
`/scan_results/` is only populated after [`scan_wifi`](https://rithvikvibhu.github.io/GHLocalApi/#operation/ScanforNetworks) is called.

**Comment by TorreJoJo** [comment]
How to do a POST with `curl` ? 
For example if we want to CURL the command `http://example.com/setup/bluetooth/scan` how can I pass the input data?

**Comment by rithvikvibhu** [comment]
```sh
curl --header "Content-Type: application/json" \
  --request POST \
  --data '{"username":"xyz","password":"xyz"}' \
  http://localhost:3000/api/login
```
