### ISSUE TITLE
Google Home App Broadcast Endpoint

### ISSUE THREAD

**Issue by DataPools** [rithvikvibhu/GHLocalApi#70]
Does anyone here know the endpoint that the Google Home App calls when you broadcast from your phone? I've tried listening on the app traffic through Charles but have not been able to find any API calls.

**Comment by DataPools** [comment]
Turns out I can just use the Foyer API with `google.internal.home.foyer.v1.HomeControlService/ExecuteRoutineOnDevice`, but I am unable to generate any auth tokens and get the following error from GRPCurl:

```
Code: PermissionDenied
  Message: Request had insufficient authentication scopes.
```

**Comment by rithvikvibhu** [comment]
Since you've already found the gRPC service and method, probably know how to make grpc requests and stuff.

To create the protobufs for getHomeGraph and others, I used `grpc-dump` to see what request and response bodies were like. Then used this json dump to convert to protobuf v2, then to v3 by hand. More info in this comment https://github.com/rithvikvibhu/GHLocalApi/issues/39#issuecomment-650590500.

To be able to dump, the phone must trust the CA and grpc-dump must use a cert from this CA. On how to set this up: https://github.com/rithvikvibhu/GHLocalApi/issues/39#issuecomment-643406303

Check out one of the existing protos for reference: https://github.com/rithvikvibhu/GHLocalApi/issues/39#issuecomment-644959103

If/When it works, post it here if you can, I'll add it along with the others.

**Comment by DataPools** [comment]
I unfortunately only have an iPhone which doesn’t play well with grpc-dump. If someone could construct a protobuf for ExecuteRoutineOnDevice it would be much appreciated.

**Comment by rithvikvibhu** [comment]
I'm kinda busy this week. If someone else can, great. Otherwise I'll do this ~1st week of Jan

**Comment by DataPools** [comment]
Great! Thanks so much!

**Comment by DataPools** [comment]
Not sure if this can be converted directly to protobuf, but I found this code: https://github.com/iCrazeiOS/Class-Dumped-Apps/blob/11e9fc710f1ac3da7bc876319c5023b84e182811/Headers/Google%20Home%202.30.123/GHCExecuteRoutineOnDeviceRequest.h

**Comment by rithvikvibhu** [comment]
Oh interesting, nice find! Not sure if it's possible directly, but can use it as a reference when building I think.

**Comment by DataPools** [comment]
I've been experimenting on Android x86 Nougat in VMWare, but have been unable to get the Google Home app to trust my `grpc-dump` certificate? How were you able to do it?

**Comment by rithvikvibhu** [comment]
I'd first use mitmproxy to set up and confirm that the CA is trusted: https://docs.mitmproxy.org/stable/howto-install-system-trusted-ca-android/

Visit a https site in a browser and make sure mitmproxy catches it and the page loads normally.

Now that the mitmproxy's CA is trusted by the phone, use its CA to generate a specific cert for googleapis.com. The 4 lines from https://github.com/rithvikvibhu/GHLocalApi/issues/39#issuecomment-643406303 will do it.

**Comment by DataPools** [comment]
I actually just generated my cert with openssl (following your 4 commands), but I think it’s an issue with Android 7. It just doesn’t trust outside certs unless the app itself is patched.

**Comment by rithvikvibhu** [comment]
Afaik (at least as of a few months ago), the app only pins the cert for communicating with local devices (with a chromecast cert), but does not for others (like google severs).

Which CA did you use in the 3rd line? That CA (and not the `googleapis.crt`) has to be imported as **system** cert, not as a user cert.

**Comment by DataPools** [comment]
Yes, so I generated a certificate called `cert.pem` with openssl, using this command `openssl req -x509 -newkey rsa:4096 -keyout key.pem -out cert.pem -days 365`

I then followed your steps to have `grp-dump` use it with `googleapis.crt`. 

Then, I installed it on the device using this app: https://play.google.com/store/apps/details?id=net.jolivier.cert.Importer&hl=en_US&gl=US

It showed up in my system certs, so it appeared to work.

However, `grp-dump` kept getting this error `TLS handshake error from 192.168.0.105:38090: remote error: tls: unknown certificate`, so I assume it's because the Google Home App was not using the cert.

**Comment by rithvikvibhu** [comment]
Hm can't think of anything right now. I'll try it again in ~10 hours and see if anything's changed. If you figure it out, post it here and I'll update the docs.

**Comment by DataPools** [comment]
Figured it out, was a problem with my cert. I decided to switch to Charles proxy and that worked fine. 

Something interesting is that the ExecuteRoutineOnDevice request does not use protobuf, it uses some raw hex instead (with three leading zero bytes).
