### ISSUE TITLE
/setup/get_app_device_id

### ISSUE THREAD

**Issue by Zibri** [rithvikvibhu/GHLocalApi#8]
/setup/get_app_device_id

this call gets the certificate which is then used to talk to the device on port 8009

**Comment by rithvikvibhu** [comment]
Interesting. I'm yet to look into ports other than 8008. So what does 8009 do?

**Comment by rithvikvibhu** [comment]
At least I haven't found anything in the app till now

**Comment by Zibri** [comment]
on a chromecast, the android app send that request on port 8008 then does everything else on port 8009 encrypted with that certificate (I presume)

**Comment by Zibri** [comment]
port 8009 uses the same command as in port 8008 but encryped... I logged all traffic with wireshark.
you can do the same:
1) set an access point on your pc.
2) connect an android phone and the chromecast to that access point.
3) run wireshark and intercept traffic..

:D

**Comment by Zibri** [comment]
if you want to further discuss this, add me on facebook.. search Zibri and add the "person" non the page :D

**Comment by Zibri** [comment]
by the way, the data in the post
`"app_id": "E8C28D3C"`
it's the "screensaver" app id on chromecast (meaning the chromecast itself)
specifying other app ids I think will make the program talk to a specific receiver instead of the main chromecast app.

**Comment by rithvikvibhu** [comment]
Searched and didn't find a lot of useful info on the cast:// protocol on port 8009. Without being able to break the encryption, I guess we're stuck here. And yeah, I'll add you on Facebook.

**Comment by rithvikvibhu** [comment]
And thanks for the app_id, will update the docs.

**Comment by Zibri** [comment]
there is no encryption to break!!! the certificate returned from this function IS THE KEY to encrypt/decrypt data on port 8009

**Comment by Zibri** [comment]
The request returns a JSON object containing:
app_device_id
certificate
signed_data

**Comment by Zibri** [comment]
http://cocoadocs.org/docsets/google-cast-sdk/3.4.0/Protocols/GCKDeviceSetupChannelDelegate.html

**Comment by Zibri** [comment]
and you can read more here: https://www.npmjs.com/package/castv2

**Comment by rithvikvibhu** [comment]
@Zibri Ah, I was thinking of this when you mentioned encryption: https://github.com/dz0ny/leapcast/issues/130
Will have to read up a bit on it.

**Comment by rithvikvibhu** [comment]
Closing this for now
